create table plane
(id bigint not null auto_increment,
 status varchar(10),
created_by bigint,
last_modified_by bigint,
created_date date,
created_at datetime(6),
last_modified_at datetime(6),
name varchar(100),
sheet int,
image varchar(500),
price varchar(100),
old int,
weight varchar(100),
fuel varchar(100),
speed varchar(100),
`range` varchar(200),
`primary` varchar(100),
 primary key (id)) engine=InnoDB AUTO_INCREMENT=1;
